name: Cucumber Test Upload to QMetry

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT: TBC
  FILE_NAME: Cucumber.json
  TESTING_TYPE: CUCUMBER
  SKIP_WARNING: 1
  IS_MATCHING_REQUIRED: 'false'
  # RELEASE_ID:
  # CYCLE_ID:
  # BUILD_ID:
  # PLATFORM_ID:
  # TESTSUITE_NAME:
  # TESTSUITE_ID:
  # TESTSUITE_FOLDER_PATH:
  # AUTOMATION_HIERARCHY:
  # TESTCASE_FIELDS:
  # TESTSUITE_FIELDS:

jobs:
  upload-cucumber-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Upload Cucumber Results to QMetry
        run: |
          FINAL_RESPONSE="$(curl --location \
            --request POST "﻿﻿https://testmanagement.qmetry.com/rest/import/createandscheduletestresults/1" \
            --header "project:$PROJECT" \
            --header "apiKey:T0cEQJ1G5r8ztbyH4lsPI9IvWe3yV3moPpgQ375v" \
            --form "file=@$FILE_NAME" \
            --form "entityType=$TESTING_TYPE" \)"
          echo "API Response = $FINAL_RESPONSE"
